# Redirects all sub pages to root index.html since routing is handled by JS.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  ignore = "git log -1 --pretty=%B | grep dependabot"
