export default {
  MAP_BACKGROUND: 'achtergrond',
  GEO: 'geo',
  DRAWING_GEOMETRY: 'tekening',
  DETAIL: 'detail',
  VIEW: 'modus',
  CATEGORY: 'categorie',
  VIEW_CENTER: 'center',
  ZOOM: 'zoom',
  LEGEND: 'legenda',
  HEADING: 'heading',
  PANORAMA_TAGS: 'tags',
  PITCH: 'pitch',
  DETAIL_REFERENCE: 'detail-ref',
  PAGE_REFERENCE: 'page-ref',
  EMBED_PREVIEW: 'embed-preview',
  EMBED: 'embed',
  PRINT: 'print',
  LAYERS: 'lagen',
  LOCATION: 'locatie',
  MARKER: 'marker',
  MARKER_ICON: 'marker-icon',
  MAP_LINK: 'map-link',
}
