export * as ligplaats from './v1.1/ligplaats'
export * as nummeraanduiding from './v1.1/nummeraanduiding'
export * as pand from './v1.1/pand'
export * as standplaats from './v1.1/standplaats'
export * as verblijfsobject from './v1.1/verblijfsobject'
export * as woonplaats from './v1.1/woonplaats'
export * as openbareRuimte from './v1.1/openbare_ruimte'
